name: GitHub CI

on:
  push:
    paths:
      - 'nerf/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'nerf/**'
      - 'tests/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] #, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@master

    - name: Set up Python environment
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip and wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Install package
      run: pip install .

    - name: Install testing dependencies
      run: pip install pylint pytest

    - name: Check code formatting
      run: pylint `find ./nerf ./tests -name '*.py'`

    - name: Install mdtraj
      run: pip install mdtraj

    - name: Run testcases
      run: pytest --disable-pytest-warnings ./tests

  coverage:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python environment
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Update pip and wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    - name: Install package
      run: pip install .

    - name: Install testing dependencies
      run: pip install pytest coverage mdtraj

    - name: generate report
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
